import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import CursorCircle from '@/components/cursorCircle'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>
          HELLO
        </h1>
        <h2>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint adipisci blanditiis praesentium voluptatem dolorum ducimus veniam omnis ipsum minus consectetur maiores, consequatur corporis magni atque et architecto explicabo ad alias.
        </h2>
        aadasdasdasdasd
      </main>
      <CursorCircle />
    </>
  )
}
