import Head from 'next/head'
import { Montserrat } from 'next/font/google'
import CursorCircle from '@/components/cursorCircle'
import Hero from '@/components/hero'
import KeyFeatures from '@/components/keyFeatures'

const montserrat = Montserrat({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${montserrat.className}`}>
        <Hero/>
        <KeyFeatures/>
      </main>
      <CursorCircle />
    </>
  )
}
